version: 0.2
env:
  variables:
    APP_NAME: "pension-management-system"
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo install process started
      - npm install --legacy-peer-deps && npm install -g @angular/cli
  build:
    commands:
      - echo build process started now
      - ng build --configuration=production
  post_build:
    commands:
      - echo build process finished, we should uplload to S3 now
      - cd dist/$APP_NAME
      - ls -la
      - aws s3 sync . s3://pension-management-system --delete
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
